/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_holding_smile_tools_TbUtil */

#ifndef _Included_com_holding_smile_tools_TbUtil
#define _Included_com_holding_smile_tools_TbUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_holding_smile_tools_TbUtil
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_holding_smile_tools_TbUtil_init__
  (JNIEnv *, jclass);

/*
 * Class:     com_holding_smile_tools_TbUtil
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_holding_smile_tools_TbUtil_init__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_holding_smile_tools_TbUtil
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_holding_smile_tools_TbUtil_cleanup
  (JNIEnv *, jclass);

/*
 * Class:     com_holding_smile_tools_TbUtil
 * Method:    cshTb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_holding_smile_tools_TbUtil_cshTb
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
