//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 04:05:32 ÏÂÎç CST 
//


package com.flyhz.avengers.framework.config.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for domain complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="domain">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="urlFilterBeforeCrawl" type="{http://www.flyhz.com/avengrs}filter" minOccurs="0"/>
 *         &lt;element name="crawlEvents" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="event" type="{http://www.flyhz.com/avengrs}event" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="urlFilterAfterCrawl" type="{http://www.flyhz.com/avengrs}filter" minOccurs="0"/>
 *         &lt;element name="templates" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="template" type="{http://www.flyhz.com/avengrs}template" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="root" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "domain", propOrder = {

})
public class Domain {

    protected Filter urlFilterBeforeCrawl;
    protected Domain.CrawlEvents crawlEvents;
    protected Filter urlFilterAfterCrawl;
    protected Domain.Templates templates;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String root;

    /**
     * Gets the value of the urlFilterBeforeCrawl property.
     * 
     * @return
     *     possible object is
     *     {@link Filter }
     *     
     */
    public Filter getUrlFilterBeforeCrawl() {
        return urlFilterBeforeCrawl;
    }

    /**
     * Sets the value of the urlFilterBeforeCrawl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filter }
     *     
     */
    public void setUrlFilterBeforeCrawl(Filter value) {
        this.urlFilterBeforeCrawl = value;
    }

    /**
     * Gets the value of the crawlEvents property.
     * 
     * @return
     *     possible object is
     *     {@link Domain.CrawlEvents }
     *     
     */
    public Domain.CrawlEvents getCrawlEvents() {
        return crawlEvents;
    }

    /**
     * Sets the value of the crawlEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Domain.CrawlEvents }
     *     
     */
    public void setCrawlEvents(Domain.CrawlEvents value) {
        this.crawlEvents = value;
    }

    /**
     * Gets the value of the urlFilterAfterCrawl property.
     * 
     * @return
     *     possible object is
     *     {@link Filter }
     *     
     */
    public Filter getUrlFilterAfterCrawl() {
        return urlFilterAfterCrawl;
    }

    /**
     * Sets the value of the urlFilterAfterCrawl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filter }
     *     
     */
    public void setUrlFilterAfterCrawl(Filter value) {
        this.urlFilterAfterCrawl = value;
    }

    /**
     * Gets the value of the templates property.
     * 
     * @return
     *     possible object is
     *     {@link Domain.Templates }
     *     
     */
    public Domain.Templates getTemplates() {
        return templates;
    }

    /**
     * Sets the value of the templates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Domain.Templates }
     *     
     */
    public void setTemplates(Domain.Templates value) {
        this.templates = value;
    }

    /**
     * Gets the value of the root property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoot() {
        return root;
    }

    /**
     * Sets the value of the root property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoot(String value) {
        this.root = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="event" type="{http://www.flyhz.com/avengrs}event" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "event"
    })
    public static class CrawlEvents {

        protected List<Event> event;

        /**
         * Gets the value of the event property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the event property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEvent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Event }
         * 
         * 
         */
        public List<Event> getEvent() {
            if (event == null) {
                event = new ArrayList<Event>();
            }
            return this.event;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="template" type="{http://www.flyhz.com/avengrs}template" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "template"
    })
    public static class Templates {

        protected List<Template> template;

        /**
         * Gets the value of the template property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the template property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTemplate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Template }
         * 
         * 
         */
        public List<Template> getTemplate() {
            if (template == null) {
                template = new ArrayList<Template>();
            }
            return this.template;
        }

    }

}
