//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 04:05:32 ÏÂÎç CST 
//


package com.flyhz.avengers.framework.config.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.flyhz.avengers.framework.config.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.flyhz.avengers.framework.config.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Domain.Templates }
     * 
     */
    public Domain.Templates createDomainTemplates() {
        return new Domain.Templates();
    }

    /**
     * Create an instance of {@link Domain.CrawlEvents }
     * 
     */
    public Domain.CrawlEvents createDomainCrawlEvents() {
        return new Domain.CrawlEvents();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link Template.TemplateApplyEvents }
     * 
     */
    public Template.TemplateApplyEvents createTemplateTemplateApplyEvents() {
        return new Template.TemplateApplyEvents();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Domain }
     * 
     */
    public Domain createDomain() {
        return new Domain();
    }

    /**
     * Create an instance of {@link Domains }
     * 
     */
    public Domains createDomains() {
        return new Domains();
    }

    /**
     * Create an instance of {@link Template }
     * 
     */
    public Template createTemplate() {
        return new Template();
    }

}
