//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.24 at 01:55:57 ионГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.flyhz.com/avengrs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.flyhz.avengers.framework.config.xml;
